# Generated by Django 3.0.4 on 2020-04-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('arrival', models.DateField(verbose_name='Arrival Date')),
                ('departure', models.DateField(verbose_name='Departure Date')),
            ],
        ),
    ]
