# Generated by Django 3.0.4 on 2020-05-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=50)),
                ('tickets', models.CharField(choices=[('Y', 'Purchased'), ('N', 'Not Purchased'), ('NA', 'Not Needed')], default='Y', max_length=2)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip')),
            ],
        ),
    ]
